import { MovieProperty } from "../../domain/types/types";
import { QuestionType, QuestionNeedsDetails } from "./types";

type QuestionTypeToEndpoint = {
  [K in QuestionType & QuestionNeedsDetails]: TmdbEndpoint;
};

type QuestionTypeToMovieProperty = {
  [K in QuestionType]: MovieProperty;
};

type Mapping = {
  [K in string]: string;
};

// Utility to reverse mapping
const reverseMapping = (object: Mapping): Mapping =>
  Object.fromEntries(
    Object.entries(object).map(([key, value]) => [value, key])
  );

export type TmdbEndpoint =
  | "/genre/movie/list"
  | "/person"
  | "/company"
  | "/keyword";

export const questionTypeToEndpoint: QuestionTypeToEndpoint = {
  genres: "/genre/movie/list",
  cast: "/person",
  crew: "/person",
  production_companies: "/company",
  keywords: "/keyword",
};

export const questionTypeToMovieProperty: QuestionTypeToMovieProperty = {
  genres: "genre_ids",
  cast: "cast",
  crew: "crew",
  years: "release_date",
  production_companies: "production_company_ids",
  keywords: "keyword_ids",
  ratings: "vote_average",
  languages: "original_language",
};

export const ratingToPhrase: Mapping = {
  "1": "Worst of your life",
  "2": "For bad-movie lovers",
  "3": "For daring allseeners",
  "4": "Low rating",
  "5": "Just an average one",
  "6": "Marginally better than average",
  "7": "Good enough",
  "8": "Must see",
  "9": "Masterpiece",
};

export const languageShortToFull: Mapping = {
  an: "Aragonese",
  ak: "Akan",
  cr: "Cree",
  az: "Azerbaijani",
  cs: "Czech",
  aa: "Afar",
  br: "Breton",
  af: "Afrikaans",
  bo: "Tibetan",
  ce: "Chechen",
  kw: "Cornish",
  fo: "Faroese",
  la: "Latin",
  ng: "Ndonga",
  sc: "Sardinian",
  ti: "Tigrinya",
  tn: "Tswana",
  tr: "Turkish",
  pa: "Punjabi",
  et: "Estonian",
  fr: "French",
  ha: "Hausa",
  is: "Icelandic",
  li: "Limburgish",
  ln: "Lingala",
  ss: "Swati",
  ab: "Abkhazian",
  sh: "Serbo-Croatian",
  eu: "Basque",
  fy: "Frisian",
  ja: "Japanese",
  oj: "Ojibwa",
  or: "Oriya",
  pi: "Pali",
  su: "Sundanese",
  th: "Thai",
  ig: "Igbo",
  id: "Indonesian",
  kk: "Kazakh",
  ki: "Kikuyu",
  ug: "Uighur",
  ve: "Venda",
  rw: "Kinyarwanda",
  mi: "Maori",
  nv: "Navajo",
  hi: "Hindi",
  pt: "Portuguese",
  sg: "Sango",
  sk: "Slovak",
  sr: "Serbian",
  ty: "Tahitian",
  xh: "Xhosa",
  ar: "Arabic",
  co: "Corsican",
  bi: "Bislama",
  eo: "Esperanto",
  hz: "Herero",
  fi: "Finnish",
  iu: "Inuktitut",
  lv: "Latvian",
  it: "Italian",
  nl: "Dutch",
  kn: "Kannada",
  sa: "Sanskrit",
  sq: "Albanian",
  tl: "Tagalog",
  lb: "Letzeburgesch",
  ts: "Tsonga",
  ml: "Malayalam",
  vo: "Volapük",
  zu: "Zulu",
  os: "Ossetian; Ossetic",
  sm: "Samoan",
  za: "Zhuang",
  bn: "Bengali",
  cu: "Slavic",
  ga: "Irish",
  gv: "Manx",
  hu: "Hungarian",
  jv: "Javanese",
  kr: "Kanuri",
  km: "Khmer",
  ky: "Kirghiz",
  na: "Nauru",
  nr: "Ndebele",
  oc: "Occitan",
  ro: "Romanian",
  ru: "Russian",
  hy: "Armenian",
  ch: "Chamorro",
  xx: "No Language",
  ba: "Bashkir",
  gl: "Galician",
  io: "Ido",
  lu: "Luba-Katanga",
  mh: "Marshall",
  mg: "Malagasy",
  mo: "Moldavian",
  mn: "Mongolian",
  nd: "Ndebele",
  no: "Norwegian",
  pl: "Polish",
  sw: "Swahili",
  tg: "Tajik",
  to: "Tonga",
  wa: "Walloon",
  yi: "Yiddish",
  en: "English",
  as: "Assamese",
  gd: "Gaelic",
  kl: "Kalaallisut",
  my: "Burmese",
  qu: "Quechua",
  sn: "Shona",
  uk: "Ukrainian",
  fa: "Persian",
  ka: "Georgian",
  gu: "Gujarati",
  av: "Avaric",
  ae: "Avestan",
  gn: "Guarani",
  mt: "Maltese",
  ne: "Nepali",
  sv: "Swedish",
  tt: "Tatar",
  wo: "Wolof",
  cn: "Cantonese",
  cv: "Chuvash",
  da: "Danish",
  dz: "Dzongkha",
  ny: "Chichewa; Nyanja",
  rn: "Rundi",
  st: "Sotho",
  tk: "Turkmen",
  uz: "Uzbek",
  vi: "Vietnamese",
  el: "Greek",
  ca: "Catalan",
  cy: "Welsh",
  de: "German",
  ks: "Kashmiri",
  ms: "Malay",
  nb: "Norwegian Bokmål",
  rm: "Raeto-Romance",
  si: "Sinhalese",
  es: "Spanish",
  te: "Telugu",
  tw: "Twi",
  ps: "Pushto",
  bg: "Bulgarian",
  mk: "Macedonian",
  ik: "Inupiaq",
  ko: "Korean",
  lt: "Lithuanian",
  om: "Oromo",
  se: "Northern Sami",
  so: "Somali",
  ta: "Tamil",
  ur: "Urdu",
  am: "Amharic",
  bs: "Bosnian",
  dv: "Divehi",
  ay: "Aymara",
  bm: "Bambara",
  ii: "Yi",
  ie: "Interlingue",
  kv: "Komi",
  ku: "Kurdish",
  nn: "Norwegian Nynorsk",
  zh: "Mandarin",
  he: "Hebrew",
  ee: "Ewe",
  fj: "Fijian",
  ff: "Fulah",
  ht: "Haitian; Haitian Creole",
  hr: "Croatian",
  ia: "Interlingua",
  kj: "Kuanyama",
  lo: "Lao",
  lg: "Ganda",
  mr: "Marathi",
  sd: "Sindhi",
  be: "Belarusian",
  ho: "Hiri Motu",
  kg: "Kongo",
  sl: "Slovenian",
  yo: "Yoruba",
};
